# Generated by Django 4.0.3 on 2022-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=b'I00\n', null=b'I00\n', upload_to='photos/'),
        ),
    ]
