# Generated by Django 4.0.3 on 2022-03-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('name',)},
        ),
    ]
