# Generated by Django 4.0.3 on 2022-03-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_dep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='dep',
        ),
    ]
