# Generated by Django 4.0.3 on 2022-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_category_location_alter_image_options_image_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=b'I00\n', null=b'I00\n', upload_to='pics/'),
        ),
    ]
