# Generated by Django 4.0.3 on 2022-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
